services:
  - type: web
    name: silver-service-online
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.0.0
